name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npmjs
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: CI
        env:
          BD_USERNAME: ${{ secrets.BD_USERNAME }}
          BD_PASSWORD: ${{ secrets.BD_PASSWORD }}
        run: |
          yarn install
          yarn build
          yarn lint
          yarn test
