name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: npmjs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: CI
        env:
          BD_USERNAME: ${{ secrets.BD_USERNAME }}
          BD_PASSWORD: ${{ secrets.BD_PASSWORD }}
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn lint
          yarn test
